# meta_product_name: "Anubatir"
# meta_title: "Anubatir - Ensam nou construire to vision"
# meta_description: "Anubatir is a privately owned, internationally focussed engineering enterprise with world-class capabilities
# spanning the entire client value chain. We operate an integrated business model comprising the full range of engineering,
# construction and asset management services delivering single-source solutions for some of the world's most prestigious public and private organisations."
# meta_image: "bannerimage.jpg" # should exist in `app/assets/images/`
